/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package javaraytracer.GUI;


import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaraytracer.Draw;
import javaraytracer.Javaraytracer;
import javaraytracer.Scena.Material;
import javaraytracer.Scena.*;
import javaraytracer.Strukture.Color;
import javaraytracer.Strukture.Point;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
/**
 *
 * @author Bijesni Patuljak
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    ImageIcon slika = new ImageIcon("output.jpg");
    Sphere LastSphere = new Sphere(new Point (0,0,0),0, new Material(new Color(0,0,0),0,0));
    Light LastLight = new Light(new Point (0,0,0), new Color (0,0,0));
    
    
    public NewJFrame() {
        initComponents();
        Labela.setText("");
        Labela.setIcon(slika);
        setTitle("Ray Tracing u Javi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Labela = new javax.swing.JLabel();
        RedValue = new javax.swing.JTextField();
        BlueValue = new javax.swing.JTextField();
        SpecValue = new javax.swing.JTextField();
        RefValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GreenValue = new javax.swing.JTextField();
        YValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        XValue = new javax.swing.JTextField();
        ZValue = new javax.swing.JTextField();
        RemoveSphere = new javax.swing.JButton();
        AddSphere = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        RValue = new javax.swing.JTextField();
        LYValue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LXValue = new javax.swing.JTextField();
        LZValue = new javax.swing.JTextField();
        RemoveLight = new javax.swing.JButton();
        AddLight = new javax.swing.JButton();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ray Tracing u Javi");
        setSize(new java.awt.Dimension(1440, 1200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Labela.setText("Labela");
        Labela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RedValue.setColumns(3);
        RedValue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RedValue.setName(""); // NOI18N
        RedValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedValueActionPerformed(evt);
            }
        });

        BlueValue.setColumns(3);
        BlueValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueValueActionPerformed(evt);
            }
        });

        SpecValue.setColumns(3);

        RefValue.setColumns(3);
        RefValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefValueActionPerformed(evt);
            }
        });

        jLabel1.setText("Red");

        jLabel2.setText("Blue");

        jLabel3.setText("Green");

        jLabel4.setText("Reflection");

        jLabel5.setText("Specular Power");

        GreenValue.setColumns(3);

        YValue.setColumns(4);

        jLabel6.setText("X");

        jLabel7.setText("Z");

        jLabel8.setText("Y");

        XValue.setColumns(4);

        ZValue.setColumns(4);

        RemoveSphere.setText("Remove Last");
        RemoveSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSphereActionPerformed(evt);
            }
        });

        AddSphere.setText("Add Sphere");
        AddSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSphereActionPerformed(evt);
            }
        });

        jLabel9.setText("Radius");

        RValue.setColumns(3);
        RValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RValueActionPerformed(evt);
            }
        });

        LYValue.setColumns(4);

        jLabel10.setText("Light X");

        jLabel11.setText("Light Z");

        jLabel12.setText("Light Y");

        LXValue.setColumns(4);

        LZValue.setColumns(4);

        RemoveLight.setText("Remove Last");
        RemoveLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLightActionPerformed(evt);
            }
        });

        AddLight.setText("Add Light");
        AddLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLightActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(BlueValue, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                                    .addComponent(GreenValue)
                                                    .addComponent(RedValue))
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ZValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(YValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(XValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(RValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(151, 151, 151)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(LZValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(LYValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(LXValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RefValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SpecValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(170, 170, 170)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RemoveSphere))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddLight, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RemoveLight))))
                                .addGap(47, 47, 47)
                                .addComponent(Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Labela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(RedValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(GreenValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(BlueValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(XValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(YValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(ZValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(LXValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(LYValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LZValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RefValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveSphere)
                            .addComponent(RValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(SpecValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddSphere)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RemoveLight)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddLight)
                            .addComponent(Update))))
                .addGap(18, 18, 18)
                .addComponent(Labela)
                .addGap(222, 222, 222)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveSphereActionPerformed
        // TODO add your handling code here:
        Javaraytracer.scene.spheres.remove(LastLight);
        try {
            Draw.draw("output1.bmp",Javaraytracer.scene);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RemoveSphereActionPerformed

    private void RedValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RedValueActionPerformed

    private void RefValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefValueActionPerformed

    private void RValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RValueActionPerformed

    private void RemoveLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLightActionPerformed
        // TODO add your handling code here:
        Javaraytracer.scene.lights.remove(LastLight);
        try {
            Draw.draw("output1.bmp",Javaraytracer.scene);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RemoveLightActionPerformed

    private void AddLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLightActionPerformed
        // TODO add your handling code here:
        int X, Y, Z;
        if(!LXValue.getText().isEmpty()) X = Integer.parseInt(LXValue.getText());
        else X = 0;
        if(!LYValue.getText().isEmpty()) Y = Integer.parseInt(LYValue.getText());
        else Y = 0;
        if(!LZValue.getText().isEmpty()) Z = Integer.parseInt(LZValue.getText());
        else Z = 0;

        Light Yagami = new Light(new Point(X, Y, Z), new Color(2.0, 2.0, 2.0));
        Javaraytracer.scene.addLight(Yagami);
        LastLight = Yagami;
        try {
            Draw.draw("output1.bmp",Javaraytracer.scene);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AddLightActionPerformed

    private void AddSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSphereActionPerformed
        // TODO add your handling code here:
        double R, G, B, spec, ref;
        int X, Y, Z, Rad;
        if(!RedValue.getText().isEmpty()) R = Double.parseDouble(RedValue.getText())/255;
        else R = 0;
        if(!GreenValue.getText().isEmpty()) G = Double.parseDouble(GreenValue.getText())/255;
        else G = 0;
        if(!BlueValue.getText().isEmpty()) B = Double.parseDouble(BlueValue.getText())/255;
        else B = 0;
        if(!SpecValue.getText().isEmpty()) spec = Double.parseDouble(SpecValue.getText())/255;
        else spec = 1;
        if(!RefValue.getText().isEmpty()) ref = Double.parseDouble(RefValue.getText())/255;
        else ref = 50;
        if(!XValue.getText().isEmpty()) X = Integer.parseInt(XValue.getText());
        else X = 0;
        if(!YValue.getText().isEmpty()) Y = Integer.parseInt(YValue.getText());
        else Y = 0;
        if(!ZValue.getText().isEmpty()) Z = Integer.parseInt(ZValue.getText());
        else Z = 0;
        if(!RValue.getText().isEmpty()) Rad = Integer.parseInt(RValue.getText());
        else Rad = 0;

        Material M = new Material(new Color(R, G, B), ref, spec);
        Sphere S = new Sphere(new Point(X, Y, Z), Rad, M);
        Javaraytracer.scene.addSphere(S);
        LastSphere = S;
        try {
            Draw.draw("output1.bmp",Javaraytracer.scene);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AddSphereActionPerformed

    private void BlueValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlueValueActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:

        Labela.setVisible(false);
        File input = new File("output1.bmp");  

        BufferedImage image = null;
        try {
            image = ImageIO.read(input);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        File output = new File("output1.jpg");
        try {
            ImageIO.write(image, "jpg", output);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        ImageIcon slika = new ImageIcon("output1.jpg");

        Labela.setIcon(slika);
        Labela.invalidate();
        Labela.revalidate();
        Labela.repaint();
        Labela.updateUI();
        Labela.setVisible(true);

   
        
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public void glavna(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLight;
    private javax.swing.JButton AddSphere;
    private javax.swing.JTextField BlueValue;
    private javax.swing.JTextField GreenValue;
    private javax.swing.JTextField LXValue;
    private javax.swing.JTextField LYValue;
    private javax.swing.JTextField LZValue;
    private javax.swing.JLabel Labela;
    private javax.swing.JTextField RValue;
    private javax.swing.JTextField RedValue;
    private javax.swing.JTextField RefValue;
    private javax.swing.JButton RemoveLight;
    private javax.swing.JButton RemoveSphere;
    private javax.swing.JTextField SpecValue;
    private javax.swing.JButton Update;
    private javax.swing.JTextField XValue;
    private javax.swing.JTextField YValue;
    private javax.swing.JTextField ZValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
